class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror3'
        self.UnzipMirrorCommand = 'extract3'
        self.TarMirrorCommand = 'tar3'
        self.CancelMirror = 'cancel3'
        self.CancelAllCommand = 'cancelall3'
        self.ListCommand = 'list'
        self.StatusCommand = 'status3'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stats3'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone3'
        self.CountCommand = 'count3'
        self.WatchCommand = 'ytdl3'
        self.TarWatchCommand = 'tarytdl3'
        self.DeleteCommand = 'del3'
        self.UsageCommand = 'usage3'
        self.MediaInfoCommand = 'mediainfo3'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
